"""
End-to-End OCR Pipeline Evaluator.

Compares the text predicted by the OCR pipeline against a Ground Truth file
using the Levenshtein (Edit) Distance metric. Generates a histogram illustrating
the error distribution across the test dataset.
"""

import csv
import argparse
import matplotlib.pyplot as plt
import numpy as np
from typing import Dict, List


def read_csv_file(file_path: str, delim: str = ";") -> Dict[str, List[str]]:
    """
    Parses a detection CSV/TXT file and extracts the panel text for each image.
    
    Args:
        file_path (str): Path to the prediction or ground truth file.
        delim (str): Delimiter used in the file.
        
    Returns:
        Dict[str, List[str]]: Dictionary mapping image filenames to a list of detected texts.
    """
    panels_info: Dict[str, List[str]] = {}
    
    with open(file_path, mode='r', encoding='utf-8') as csv_file:
        csv_reader = csv.reader(csv_file, delimiter=delim)
        for row in csv_reader:
            if not row:
                continue
                
            image_name = row[0]
            # Handle cases where OCR failed and text column might be empty or missing
            try:
                panel_text = row[7]
            except IndexError:
                panel_text = "" 
                
            if image_name not in panels_info:
                panels_info[image_name] = [panel_text]
            else:
                panels_info[image_name].append(panel_text)

    return panels_info


def levenshtein_distance(str1: str, str2: str) -> int:
    """
    Calculates the minimum number of single-character edits required to 
    change str1 into str2 using Dynamic Programming (2D Matrix approach).
    """
    m, n = len(str1), len(str2)
    
    # Initialize an (m+1) x (n+1) matrix with zeros
    d = [[0] * (n + 1) for _ in range(m + 1)]
    
    # Base cases: Distance from empty string to string of length i/j
    for i in range(m + 1):
        d[i][0] = i
    for j in range(n + 1):
        d[0][j] = j
        
    # Fill the matrix
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            cost = 0 if str1[i - 1] == str2[j - 1] else 1
            d[i][j] = min(
                d[i - 1][j] + 1,       # Deletion
                d[i][j - 1] + 1,       # Insertion
                d[i - 1][j - 1] + cost # Substitution
            )

    return d[m][n]


def plot_recognition_distance(p_gt: Dict[str, List[str]], p_pred: Dict[str, List[str]]) -> None:
    """
    Computes Levenshtein distances for all image matches and plots an error histogram.
    """
    txt_distance_all = []
    
    for img_name, p_info_gt in p_gt.items():
        if img_name not in p_pred:  
            # Not found a panel in this image (Assign a high penalty or -1)
            txt_distance_all.append(-1) 
            continue

        p_info = p_pred[img_name]

        # By now we assume only one major text block for each image
        plate_gt = p_info_gt[0]
        if len(p_info) >= 1: 
            plate_pred = p_info[0]
            dist = levenshtein_distance(plate_gt, plate_pred)
            txt_distance_all.append(dist)

    valid_distances = [d for d in txt_distance_all if d >= 0]
    missing_count = txt_distance_all.count(-1)

    print(f"\n[INFO] Evaluation Complete.")
    print(f"       -> Valid text matches evaluated: {len(valid_distances)}")
    print(f"       -> Missed detections: {missing_count}")
    
    if not valid_distances:
        print("[WARNING] No valid matches found to plot.")
        return

    # Plot histogram
    plt.figure(figsize=(10, 6))
    hist, bin_edges = np.histogram(np.array(valid_distances), bins=25, density=False)
    plt.step(bin_edges[:-1], hist, where='mid', color='#1f77b4', linewidth=2)
    plt.fill_between(bin_edges[:-1], hist, step="mid", alpha=0.4, color='#1f77b4')
    
    plt.title("Levenshtein Distance: Ground Truth vs OCR Prediction", fontsize=16)
    plt.ylabel("Number of Images", fontsize=12)
    plt.xlabel("Edit Distance (Number of Operations)", fontsize=12)
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    
    plt.tight_layout()
    plt.show()


def main() -> None:
    parser = argparse.ArgumentParser(description="Evaluates OCR End-to-End results using Levenshtein distance.")
    parser.add_argument('--ground_truth', type=str, required=True, 
                        help="Path to the baseline/Ground Truth CSV/TXT file.")
    parser.add_argument('--predictions', type=str, required=True, 
                        help="Path to the predictions CSV/TXT file generated by the pipeline.")
    args = parser.parse_args()

    print("[INFO] Loading Ground Truth...")
    gt_dict = read_csv_file(args.ground_truth)
    
    print("[INFO] Loading Model Predictions...")
    pred_dict = read_csv_file(args.predictions)
    
    plot_recognition_distance(gt_dict, pred_dict)


if __name__ == "__main__":
    main()